services:

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - ./configs/config_mongo_db.env
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  sqlite-fastapi-server:
    image: alice3e/sqlite_app:latest
    ports:
      - "8000:8000"
    env_file:
      - ./configs/config_sqlite.env
    volumes:
      - sqlite_data:/app/data
    networks:
      - app-network

  mongo-fastapi-server:
    image: alice3e/mongo_app:latest
    ports:
      - "8001:8000"
    env_file:
      - ./configs/config_mongo_server.env
    depends_on:
      - mongodb
      - sqlite-fastapi-server
    networks:
      - app-network

  worker-node-control-server:
    image: alice3e/worker_node_control_server:latest
    ports:
      - "8003:8000"
    env_file:
      - ./configs/config_worker_node_control_server.env
    depends_on:
      - mongodb
      - sqlite-fastapi-server
      - mongo-fastapi-server
    networks:
      - app-network

  worker-node-1:
    image: alice3e/worker_node:latest
    ports:
      - "8004:8000"
    env_file:
      - ./configs/config_worker_node.env
    depends_on:
      - worker-node-control-server
    networks:
      - app-network
  
  worker-node-2:
    image: alice3e/worker_node:latest
    ports:
      - "8005:8000"
    env_file:
      - ./configs/config_worker_node.env
    depends_on:
      - worker-node-control-server
    networks:
      - app-network

  worker-node-3:
    image: alice3e/worker_node:latest
    ports:
      - "8006:8000"
    env_file:
      - ./configs/config_worker_node.env
    depends_on:
      - worker-node-control-server
    networks:
      - app-network

  main-server:
    image: alice3e/main_server:latest
    ports:
      - "8002:8000"
    env_file:
      - ./configs/config_main_server.env
    depends_on:
      - mongodb
      - sqlite-fastapi-server
      - mongo-fastapi-server
      - worker-node-control-server
    networks:
      - app-network


  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   env_file:
  #     - ./configs/config_mongo_db.env
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - app-network

  # sqlite-fastapi-server:
  #   build: ./sqlite_app
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./configs/config_sqlite.env
  #   volumes:
  #     - sqlite_data:/app/data
  #   networks:
  #     - app-network

  # mongo-fastapi-server:
  #   build: ./mongo_app
  #   ports:
  #     - "8001:8000"
  #   env_file:
  #     - ./configs/config_mongo_server.env
  #   depends_on:
  #     - mongodb
  #     - sqlite-fastapi-server
  #   networks:
  #     - app-network

  # worker-node-control-server:
  #   build: ./worker_node_control_server
  #   ports:
  #     - "8003:8000"
  #   env_file:
  #     - ./configs/config_worker_node_control_server.env
  #   depends_on:
  #     - mongodb
  #     - sqlite-fastapi-server
  #     - mongo-fastapi-server
  #   networks:
  #     - app-network

  # worker-node-1:
  #   build: ./worker_node
  #   ports:
  #     - "8004:8000"
  #   env_file:
  #     - ./configs/config_worker_node.env
  #   depends_on:
  #     - worker-node-control-server
  #   networks:
  #     - app-network
  
  # worker-node-2:
  #   build: ./worker_node
  #   ports:
  #     - "8005:8000"
  #   env_file:
  #     - ./configs/config_worker_node.env
  #   depends_on:
  #     - worker-node-control-server
  #   networks:
  #     - app-network

  # worker-node-3:
  #   build: ./worker_node
  #   ports:
  #     - "8006:8000"
  #   env_file:
  #     - ./configs/config_worker_node.env
  #   depends_on:
  #     - worker-node-control-server
  #   networks:
  #     - app-network

  # main-server:
  #   build: ./main_server
  #   ports:
  #     - "8002:8000"
  #   env_file:
  #     - ./configs/config_main_server.env
  #   depends_on:
  #     - mongodb
  #     - sqlite-fastapi-server
  #     - mongo-fastapi-server
  #     - worker-node-control-server
  #   networks:
  #     - app-network

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: "/Users/stepanudincev/_it/spbu/kmms_prog_2024/qt_distributed_team_project/docker_servers/db_mongo"  # Укажите путь на хосте для MongoDB
      o: bind
  sqlite_data:
    driver: local
    driver_opts:
      type: none
      device: "/Users/stepanudincev/_it/spbu/kmms_prog_2024/qt_distributed_team_project/docker_servers/db_sqlite"  # Укажите путь на хосте для SQLite
      o: bind
networks:
  app-network:
    driver: bridge
